name: Build and publish docker
description: This action should Build a docker image and publish to docker hub
inputs:
  short_sha:
    description: 'Git commit SHA'
    required: true
  build_image_script:
    description: 'The shell script that builds the docker image'
    required: true
    default: ./ci/build-and-publish-image.sh
  npm_token:
    description: 'Npm Token'
    required: true
  docker_hub_password:
    description: 'Docker Hub Password'
    required: true
  docker_hub_user:
    description: 'Docker Hub User'
    required: true



runs:
  using: "composite"
  steps:
    - name: Build and push docker image
      run: |
        echo commit hash: ${COMMIT_HASH}
        echo tag: ${TAG_NAME}
        echo branch: ${BRANCH_NAME}
        sudo chmod +x ${{ inputs.build_image_script }}
        ${{ inputs.build_image_script }}
      shell: bash
      env:
        COMMIT_HASH: ${{ inputs.short_sha }}
        TAG_NAME: ${{ github.ref_name }}
        NPM_TOKEN: ${{ inputs.npm_token }}
        DOCKER_HUB_USER: ${{ inputs.docker_hub_user }}
        DOCKER_HUB_PASSWORD: ${{ inputs.docker_hub_password }}
