name: 'Setup NPM RC files'
description: 'Sets up .npmrc or .yarnrc or .yarnrc.yml, depending on provided package manager info'
inputs:
  npm_token:
    description: 'NPM Token - read-only is enough'
    required: true
  package_manager:
    description: 'Package manager to use'
    required: true
    default: 'npm'
  package_manager_version:
    description: 'Package manager version to use'
    required: true
    default: 'latest'
  registry:
    description: 'NPM Registry address to use'
    required: true
    default: 'https://registry.npmjs.org'
  working_directory:
    description: The base path of the service code
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Setup .npmrc
      if: inputs.package_manager == 'npm' || (inputs.package_manager == 'yarn' && startsWith(inputs.package_manager_version, '1.'))
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: echo "//registry.npmjs.org/:_authToken=${{ inputs.npm_token }}" > .npmrc
    - name: Setup .yarnrc.yml
      if: inputs.package_manager == 'yarn' && !startsWith(inputs.package_manager_version, '1.')
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        yq -i '.npmRegistryServer="${{ inputs.registry }}"' .yarnrc.yml
        yq -i '.npmAuthToken="${{ inputs.npm_token }}"' .yarnrc.yml
