name: Build and Tests
description: Build and tests
inputs:
  repo:
    description: "Commit Repository"
    required: true
  dispatch_id:
    description: 'Dispatch Id (repo/sha)'
    required: false
  state:
    description: "Check State"
    default: "pending"
  description:
    description: "Check description"
    required: true
  owner:
    description: "Repo Owner"
    default: "frontegg"
    required: false
  run_context:
    description: "Run Context"
    default: "frontegg/e2e-system-tests"
    required: false

runs:
  using: "composite"
  steps:
    - id: create_bot_token
      name: Create bot token
      uses: wow-actions/use-app-token@v2
      with:
        app_id: ${{ secrets.GH_FRONTEGG_BOT_APP_ID }}
        private_key: ${{ secrets.GH_FRONTEGG_BOT_APP_SECRET }}
    - name: Update PR Status
      uses: actions/github-script@v5
      env:
        dispatch_id: ${{ inputs.dispatch_id }}
        state: ${{ inputs.state }}
        description: ${{ inputs.description }}
        owner: ${{ inputs.owner }}
        run_context: ${{ inputs.run_context }}
      with:
        github-token: ${{ env.BOT_TOKEN }}
        script: |
          const {dispatch_id,state, description, owner, run_context} = process.env
          if(dispatch_id){
            const [repo, sha] = dispatch_id.split('/')
            const res = await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state,
              description,
              context: run_context
            });
          } else {
            console.log("skip update, dispatch id not found")
          }
