name: Wait for venv
description: Wait for venv to be ready
inputs:
  argocd_password:
    description: 'Admin github token'
    required: true
  environmentId:
    description: 'Set the created venv Ud'
    required: true
  apiUrl:
    description: 'Set the created venv api gateway url'
    required: true
  waitTimeout:
    description: 'Set the wait timeout'
    required: false
    default: "900"

runs:
  using: "composite"
  steps:
    - name: Wait for ArgoCD
      uses: whatnick/wait-action@master
      with:
        time: '3m'
    - uses: clowdhaus/argo-cd-action/@main
      name: Login local ArgoCD
      with:
        version: 2.7.3
        command: login
        options: argocd-server.argocd.svc.cluster.local --insecure --plaintext --username admin --password ${{ inputs.argocd_password }}
    - uses: clowdhaus/argo-cd-action/@main
      name: Wait for venv to be ready
      with:
        version: 2.7.3
        command: app wait -l venv=${{ inputs.environmentId }} --timeout ${{ inputs.waitTimeout }}
    - name: Check access to the environment
      uses: mydea/action-wait-for-api@v1
      with:
        url: ${{ inputs.apiUrl }}/test
