name: Progressive Delivery - Canary Release

on: workflow_dispatch

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    name: Run E2E Tests
    steps:
      - name: Say that you are testing
        run: echo "Testing......!"
      - name: Say that testing is done
        run: echo "Completed......!"