name: Progressive Delivery - Canary Release
run-name: Deploying ${{inputs.version}} to ${{inputs.service}}

on: 
  workflow_dispatch:
    inputs:
      service:
        description: 'Service being deployed'
        required: true
      version:
        description: 'Version being deployed'
        required: true
      fail:
        description: 'Fail the deployment'
        required: false
        default: 'false'
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    name: Run E2E Tests
    steps:
      - name: Say that you are testing
        run: echo "Testing ${{inputs.service}} ${{inputs.version}} ...!"
      - name: Wait for 7 seconds
        run: sleep 7
      - name: Validate failure
        run: |
          if [ "${{inputs.fail}}" = "true" ]; then
            echo "Tests failed on ${{inputs.service}} ${{inputs.version}}...!"
            exit 1
          fi
          echo "Completed ${{inputs.service}} ${{inputs.version}}..."