name: Full Suite Test (API + E2E On Venv)
on:
  workflow_call:
    inputs:
      build_image:
        type: boolean
        required: false
        description: This has no effect on this workflow any more, should be remoeved when all services will remove it
        default: false
      tests_tag:
        type: string
        required: false
        description: Set the e2e-api tests branch tag
        default: master
    secrets:
      GH_REPOSITORY_ADMIN_TOKEN:
        description: 'Github repository admin token'
        required: true
      DEV_ARGOCD_PASSWORD:
        description: 'ArgoCD password'
        required: true
      NPM_TOKEN:
        description: 'Npm token'
        required: true
      DOCKER_HUB_ACTION_USER:
        description: 'Docker hub user'
        required: true
      DOCKER_HUB_ACTION_PASSWORD:
        description: 'Docker hub password'
        required: true
      MAILOSAUR_API_KEY:
        description: 'MAILOSAUR API KEY'
        required: true
      MAILOSAUR_SERVER_ID:
        description: 'MAILOSAUR SERVER ID'
        required: true
      MAILOSAUR_SERVER_DOMAIN:
        description: 'MAILOSAUR SERVER DOMAIN'
        required: true
      ZEPHYR_TOKEN:
        description: ''
        required: true

jobs:
  start-venv:
    name: Start venv
    uses: frontegg/workflows/.github/workflows/start-venv.yaml@master
    with:
      volatileEnvironment: true
    secrets:
      GH_REPOSITORY_ADMIN_TOKEN: ${{ secrets.GH_REPOSITORY_ADMIN_TOKEN }}
      DEV_ARGOCD_PASSWORD: ${{ secrets.DEV_ARGOCD_PASSWORD }}
      NPM_TOKEN : ${{ secrets.NPM_TOKEN }}
      DOCKER_HUB_ACTION_USER : ${{ secrets.DOCKER_HUB_ACTION_USER }}
      DOCKER_HUB_ACTION_PASSWORD : ${{ secrets.DOCKER_HUB_ACTION_PASSWORD }}
      SLACK_VENV_WEBHOOK: ${{ secrets.SLACK_VENV_WEBHOOK }}

  prepare-params:
    name: Prepare environment params
    runs-on: ubuntu-latest
    needs: [ start-venv ]
    outputs:
      apiUrl: ${{ steps.variables.outputs.apiUrl }}
      portalUrl: ${{ steps.variables.outputs.portalUrl }}
      environmentId: ${{ steps.variables.outputs.environmentId }}
    steps:
      - name: prepare output params
        id: variables
        run: |
          echo "environmentId=${{ needs.start-venv.outputs.environmentId }}" >> $GITHUB_OUTPUT
          echo "apiUrl=${{ needs.start-venv.outputs.apiUrl }}" >> $GITHUB_OUTPUT
          echo "portalUrl=${{ needs.start-venv.outputs.portalUrl }}" >> $GITHUB_OUTPUT

  run-e2e-test:
    runs-on: ubuntu-latest
    needs: [ prepare-params ]
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
        with:
          repository: frontegg/e2e-system-tests
          ref: ${{ inputs.tests_tag }}
          token: ${{ secrets.GH_REPOSITORY_ADMIN_TOKEN }}

      - name: Run E2E Tests from E2E-system-tests repo
        uses: ./.github/actions/e2e-test
        with:
          github_token: ${{ secrets.GH_REPOSITORY_ADMIN_TOKEN }}
          npm_token: ${{ secrets.NPM_TOKEN }}
          server_url: ${{ needs.prepare-params.outputs.apiUrl }}
          portal_url: ${{ needs.prepare-params.outputs.portalUrl }}
          twilio_account_id: ${{ secrets.TWILIO_TEST_ACCOUND_ID }}
          twilio_token: ${{ secrets.TWILIO_TEST_TOKEN }}
          MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}
          MAILOSAUR_SERVER_ID: ${{ secrets.MAILOSAUR_SERVER_ID }}
          MAILOSAUR_SERVER_DOMAIN: ${{ secrets.MAILOSAUR_SERVER_DOMAIN }}
          ZEPHYR_TOKEN: ${{ secrets.ZEPHYR_TOKEN }}

  run-api-test:
    runs-on: ubuntu-latest
    needs: [ prepare-params ]
    if: |
      always() &&
      !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
        with:
          repository: frontegg/e2e-system-tests
          ref: ${{ inputs.tests_tag }}
          token: ${{ secrets.GH_REPOSITORY_ADMIN_TOKEN }}

      - name: Run API Tests from E2E-system-tests repo
        uses: ./.github/actions/api-tests
        with:
          github_token: ${{ secrets.GH_REPOSITORY_ADMIN_TOKEN }}
          npm_token: ${{ secrets.NPM_TOKEN }}
          server_url: ${{ needs.prepare-params.outputs.apiUrl }}
          portal_url: ${{ needs.prepare-params.outputs.portalUrl }}
          twilio_account_id: ${{ secrets.TWILIO_TEST_ACCOUND_ID }}
          twilio_token: ${{ secrets.TWILIO_TEST_TOKEN }}
          MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}
          MAILOSAUR_SERVER_ID: ${{ secrets.MAILOSAUR_SERVER_ID }}
          MAILOSAUR_SERVER_DOMAIN: ${{ secrets.MAILOSAUR_SERVER_DOMAIN }}
          ZEPHYR_TOKEN: ${{ secrets.ZEPHYR_TOKEN }}

  remove-venv:
    name: Remove venv
    needs: [ run-api-test, run-e2e-test, start-venv, prepare-params ]
    if: |
      always() &&
      (needs.prepare-params.outputs.environmentId) &&
      contains(needs.*.result, 'success')
    uses: frontegg/workflows/.github/workflows/remove-single-venv.yaml@master
    with:
      venvId: ${{ needs.prepare-params.outputs.environmentId }}
      gracePeriodInMinutes: "${{ (needs.start-venv.result == 'failure') && '15' || '0' }}"
    secrets:
      admin_github_token: ${{ secrets.GH_REPOSITORY_ADMIN_TOKEN }}
