name: Main Service Deployment Workflow

on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
      repository_name:
        type: string
        required: true
      has_hybrid:
        required: false
        default: false
        type: boolean
      staging_environment_name:
        required: false
        default: staging
        type: string
      au_environment_name:
        required: false
        default: production-au
        type: string
      us_environment_name:
        required: false
        default: production-us
        type: string
      global_environment_name:
        required: false
        default: production-global
        type: string
      build_image_script:
        required: false
        default: ./ci/build-and-publish-image.sh
        type: string
      build_hybrid_image_script:
        required: false
        default: ./ci/build-and-publish-hybrid-image.sh
        type: string
      contains_code_changes:
        required: false
        default: true
        type: boolean
      ref:
        required: false
        default: ""
        type: string
      workflows_version:
        required: false
        default: ""
        type: string
    secrets:
      npm_token:
        description: 'Npm Token'
        required: true
      docker_hub_password:
        description: 'Docker Hub Password'
        required: true
      docker_hub_user:
        description: 'Docker Hub User'
        required: true
      admin_github_token:
        description: 'Github repository admin token'
        required: true
      slack_production_webhook:
        description: 'Slack webhook token'
        required: false

jobs:
  main-with-image:
    name: Build Image and deploy
    if: ${{ inputs.contains_code_changes }}
    uses: frontegg/workflows/.github/workflows/main-with-image.yaml@emergecny-deployment-2
    with:
      tag: ${{ inputs.tag }}
      repository_name: ${{ inputs.repository_name }}
      has_hybrid: ${{ inputs.has_hybrid }}
      staging_environment_name: ${{ inputs.staging_environment_name }}
      au_environment_name: ${{ inputs.au_environment_name }}
      us_environment_name: ${{ inputs.us_environment_name }}
      global_environment_name: ${{ inputs.global_environment_name }}
      build_image_script: ${{ inputs.build_image_script }}
      build_hybrid_image_script: ${{ inputs.build_hybrid_image_script }}
      ref: ${{ inputs.ref }}
      workflows_version: ${{ inputs.workflows_version }}
    secrets:
      npm_token: ${{ secrets.npm_token }}
      docker_hub_password: ${{ secrets.docker_hub_password }}
      docker_hub_user: ${{ secrets.docker_hub_user }}
      admin_github_token: ${{ secrets.admin_github_token }}
      slack_production_webhook: ${{ secrets.slack_production_webhook }}

  main-without-image:
    name: Deploy
    if: ${{ !inputs.contains_code_changes }}
    uses: frontegg/workflows/.github/workflows/main-without-image.yaml@emergecny-deployment-2
    with:
      tag: ${{ inputs.tag }}
      repository_name: ${{ inputs.repository_name }}
      has_hybrid: ${{ inputs.has_hybrid }}
      staging_environment_name: ${{ inputs.staging_environment_name }}
      au_environment_name: ${{ inputs.au_environment_name }}
      us_environment_name: ${{ inputs.us_environment_name }}
      global_environment_name: ${{ inputs.global_environment_name }}
      build_image_script: ${{ inputs.build_image_script }}
      build_hybrid_image_script: ${{ inputs.build_hybrid_image_script }}
      ref: ${{ inputs.ref }}
      workflows_version: ${{ inputs.workflows_version }}
    secrets:
      npm_token: ${{ secrets.npm_token }}
      docker_hub_password: ${{ secrets.docker_hub_password }}
      docker_hub_user: ${{ secrets.docker_hub_user }}
      admin_github_token: ${{ secrets.admin_github_token }}
      slack_production_webhook: ${{ secrets.slack_production_webhook }}
