name: Main Service Deployment Workflow

on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
      repository_name:
        type: string
        required: true
      has_hybrid:
        required: false
        default: false
        type: boolean
      staging_environment_name:
        required: false
        default: staging
        type: string
      au_environment_name:
        required: false
        default: production-au
        type: string
      us_environment_name:
        required: false
        default: production-us
        type: string
      global_environment_name:
        required: false
        default: production-global
        type: string
      build_image_script:
        required: false
        default: ./ci/build-and-publish-image.sh
        type: string
      build_hybrid_image_script:
        required: false
        default: ./ci/build-and-publish-hybrid-image.sh
        type: string
      ref:
        required: false
        default: ""
        type: string
      workflows_version:
        required: false
        default: ""
        type: string
    secrets:
      npm_token:
        description: 'Npm Token'
        required: true
      docker_hub_password:
        description: 'Docker Hub Password'
        required: true
      docker_hub_user:
        description: 'Docker Hub User'
        required: true
      admin_github_token:
        description: 'Github repository admin token'
        required: true
      slack_production_webhook:
        description: 'Slack webhook token'
        required: false

jobs:
  check-changes:
    name: Check Changes
    runs-on: ubuntu-latest
    outputs:
      code_change: ${{ steps.changes.outputs.code-change }}
      chart_change: ${{ steps.changes.outputs.chart-change }}
    steps:
      - name: Checkout ${{ inputs.repository_name }}
        uses: actions/checkout@v4
        with:
          repository: frontegg/${{ inputs.repository_name }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.admin_github_token }}
      - uses: AurorNZ/paths-filter@v3
        id: changes
        with:
          filters: |
            code-change:
              - '**'
              - '!k8s/**'
            chart-change:
              - '!**'
              - 'k8s/**'

  main-with-image:
    name: Build Image and deploy
    if: ${{ needs.check-changes.outputs.code_change }}
    needs: [ check-changes ]
    uses: frontegg/workflows/.github/workflows/main-with-image.yaml@master
    with:
      tag: ${{ inputs.tag }}
      repository_name: ${{ inputs.repository_name }}
      has_hybrid: ${{ inputs.has_hybrid }}
      staging_environment_name: ${{ inputs.staging_environment_name }}
      au_environment_name: ${{ inputs.au_environment_name }}
      us_environment_name: ${{ inputs.us_environment_name }}
      global_environment_name: ${{ inputs.global_environment_name }}
      build_image_script: ${{ inputs.build_image_script }}
      build_hybrid_image_script: ${{ inputs.build_hybrid_image_script }}
      ref: ${{ inputs.ref }}
      workflows_version: ${{ inputs.workflows_version }}
      code_changed: ${{ needs.check-changes.outputs.code_change }}
      chart_changed: ${{ needs.check-changes.outputs.chart_change }}
    secrets:
      npm_token: ${{ secrets.npm_token }}
      docker_hub_password: ${{ secrets.docker_hub_password }}
      docker_hub_user: ${{ secrets.docker_hub_user }}
      admin_github_token: ${{ secrets.admin_github_token }}
      slack_production_webhook: ${{ secrets.slack_production_webhook }}

  main-without-image:
    name: Deploy
    if: ${{ needs.check-changes.outputs.code_change == false && needs.check-changes.outputs.chart_change }}
    needs: [ check-changes ]
    uses: frontegg/workflows/.github/workflows/main-without-image.yaml@master
    with:
      tag: ${{ inputs.tag }}
      repository_name: ${{ inputs.repository_name }}
      has_hybrid: ${{ inputs.has_hybrid }}
      staging_environment_name: ${{ inputs.staging_environment_name }}
      au_environment_name: ${{ inputs.au_environment_name }}
      us_environment_name: ${{ inputs.us_environment_name }}
      global_environment_name: ${{ inputs.global_environment_name }}
      build_image_script: ${{ inputs.build_image_script }}
      build_hybrid_image_script: ${{ inputs.build_hybrid_image_script }}
      ref: ${{ inputs.ref }}
      workflows_version: ${{ inputs.workflows_version }}
      code_changed: ${{ needs.check-changes.outputs.code_change }}
      chart_changed: ${{ needs.check-changes.outputs.chart_change }}
    secrets:
      npm_token: ${{ secrets.npm_token }}
      docker_hub_password: ${{ secrets.docker_hub_password }}
      docker_hub_user: ${{ secrets.docker_hub_user }}
      admin_github_token: ${{ secrets.admin_github_token }}
      slack_production_webhook: ${{ secrets.slack_production_webhook }}
