name: POC for main workflow

on:
  workflow_call:
    inputs:
      short_sha:
        default: ${GITHUB_SHA::7}
        type: string
    secrets:
      npm_token:
        description: 'Npm Token'
        required: true
      docker_hub_password:
        description: 'Docker Hub Password'
        required: true
      docker_hub_user:
        description: 'Docker Hub User'
        required: true

jobs:
  build-docker:
    name: Build and publish docker images
    runs-on: ubuntu-latest
    steps:
      - name: Display
        run: echo ${{ inputs.short_sha }}
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Install make
#        run: sudo apt-get install make
#        shell: bash
#      - name: Make npmrc
#        run: make generate-npmrc-file NPM_TOKEN=${{ secrets.npm_token }}
#        shell: bash
#      - name: Build and push docker image with tag ${{ inputs.short_sha }}
#        run: |
#          make build-docker-image NPM_TOKEN=${{ secrets.npm_token }} COMMIT_HASH=${{ inputs.short_sha }} TAG_NAME=${{ env.BRANCH_NAME }}
#          make push-docker-image
#        shell: bash
#        env:
#          COMMIT_HASH: ${{ github.sha }}
#          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
#          DOCKER_HUB_USER: ${{ secrets.docker_hub_user }}
#          DOCKER_HUB_PASSWORD: ${{ secrets.docker_hub_password }}

  deploy-to-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    needs:
      - build-docker
#      - build-hybrid-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: frontegg/workflows
          path: .github/shared-actions
      - run: |
          apt-get install tree
          tree
        shell: bash
      - run: |
          cd .github/shared-actions
          ls -1 -a
        shell: bash
      - run: |
          cd .github/shared-actions/deploy
          ls -1 -a
        shell: bash
      - name: 'Deploy to staging'
        uses: ./.github/shared-actions/deploy
        with:
          environment: staging
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_name: ${{ github.repository }}
          docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
          docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
  us-deployment:
    needs: deploy-to-staging
    name: 'Deploy to US production'
    runs-on: ubuntu-latest
    environment:
      name: production-us
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to production US
        uses: ./.github/actions/deploy
        with:
          environment: production-us
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_name: ${{ github.repository }}
          docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
          docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
  eu-deployment:
    name: 'Deploy to EU production'
    needs: deploy-to-staging
    runs-on: ubuntu-latest
    environment:
      name: production-global
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to production global
        uses: ./.github/actions/deploy
        with:
          environment: production-global
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_name: ${{ github.repository }}
          docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
          docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
