name: Main Service Deployment Workflow Without Docker

on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
      repository_name:
        type: string
        required: true
      has_hybrid:
        required: false
        default: false
        type: boolean
      staging_environment_name:
        required: false
        default: staging
        type: string
      au_environment_name:
        required: false
        default: production-au
        type: string
      us_environment_name:
        required: false
        default: production-us
        type: string
      global_environment_name:
        required: false
        default: production-global
        type: string
      build_image_script:
        required: false
        default: ./ci/build-and-publish-image.sh
        type: string
      build_hybrid_image_script:
        required: false
        default: ./ci/build-and-publish-hybrid-image.sh
        type: string
      ref:
        required: true
        type: string
      workflows_version:
        required: false
        type: string
        default: ""
    secrets:
      npm_token:
        description: 'Npm Token'
        required: true
      docker_hub_password:
        description: 'Docker Hub Password'
        required: true
      docker_hub_user:
        description: 'Docker Hub User'
        required: true
      admin_github_token:
        description: 'Github repository admin token'
        required: true
      slack_production_webhook:
        description: 'Slack webhook token'
        required: false

jobs:
  params:
    name: Generate deployment params
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.short-sha.outputs.short_sha }}
    steps:
      - name: Checkout ${{ inputs.repository_name }}
        uses: actions/checkout@v4
        with:
          repository: frontegg/${{ inputs.repository_name }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.admin_github_token }}
      - name: Get short SHA from tag or commit
        id: get-code-sha
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
      - name: Parse short sha
        id: short-sha
        run: |
          if [ -z "${{ inputs.tag }}" ]
          then
            echo "short_sha=${{ steps.get-code-sha.outputs.sha }}" >> $GITHUB_OUTPUT
          else
            echo "short_sha=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          fi
      - run: echo short sha - ${{ steps.short-sha.outputs.short_sha }}

  deploy-to-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.staging_environment_name }}
    needs:
      - params
    steps:
      - name: Checkout ${{ inputs.repository_name }}
        uses: actions/checkout@v4
        with:
          path: code
          repository: frontegg/${{ inputs.repository_name }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.admin_github_token }}
      - name: Checkout workflows
        uses: actions/checkout@v4
        with:
          repository: frontegg/workflows
          path: workflows
          ref: ${{ inputs.workflows_version }}
      - name: 'Deploy to staging'
        uses: ./workflows/.github/shared-actions/tag-versions
        with:
          github_token: ${{ secrets.admin_github_token }}
          repository_name: ${{ inputs.repository_name }}
          environment: ${{ inputs.staging_environment_name }}
          docker_hub_user: ${{ secrets.docker_hub_user }}
          docker_hub_password: ${{ secrets.docker_hub_password }}
          current_tag: ${{ needs.params.outputs.short_sha }}
          should_tag_image: false

  deploy-to-australia:
    name: Deploy to Australia Region (Sydney)
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.au_environment_name }}
    needs:
      - params
      - deploy-to-staging
    steps:
      - name: Checkout ${{ inputs.repository_name }}
        uses: actions/checkout@v4
        with:
          path: code
          repository: frontegg/${{ inputs.repository_name }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.admin_github_token }}
      - name: Checkout workflows
        uses: actions/checkout@v4
        with:
          repository: frontegg/workflows
          path: workflows
          ref: ${{ inputs.workflows_version }}
      - name: 'Deploy to Production AU'
        uses: ./workflows/.github/shared-actions/tag-versions
        with:
          github_token: ${{ secrets.admin_github_token }}
          repository_name: ${{ inputs.repository_name }}
          environment: ${{ inputs.au_environment_name }}
          docker_hub_user: ${{ secrets.docker_hub_user }}
          docker_hub_password: ${{ secrets.docker_hub_password }}
          current_tag: ${{ needs.params.outputs.short_sha }}
          should_tag_image: false
      - name: Assign variable
        id: secret
        run: echo '::set-output name=secret::${{ secrets.slack_production_webhook }}'
      - name: Notify Slack on deployment
        if: steps.secret.outputs.secret
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: Production
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/67857107?s=40&v=4
          SLACK_MESSAGE: '${{ github.actor }} has deployed ${{ inputs.repository_name }} to ${{ inputs.au_environment_name }} :rocket:'
          SLACK_TITLE: ${{ inputs.repository_name }} to ${{ inputs.au_environment_name }}
          SLACK_USERNAME: ${{ github.actor }}
          SLACK_WEBHOOK: ${{ secrets.slack_production_webhook }}
          MSG_MINIMAL: Commit,actions url

  deploy-to-us:
    name: Deploy to US East 1
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.us_environment_name }}
    needs:
      - params
      - deploy-to-australia
    steps:
      - name: Checkout ${{ inputs.repository_name }}
        uses: actions/checkout@v4
        with:
          path: code
          repository: frontegg/${{ inputs.repository_name }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.admin_github_token }}
      - name: Checkout workflows
        uses: actions/checkout@v4
        with:
          repository: frontegg/workflows
          path: workflows
          ref: ${{ inputs.workflows_version }}
      - name: 'Deploy to Production US'
        uses: ./workflows/.github/shared-actions/tag-versions
        with:
          github_token: ${{ secrets.admin_github_token }}
          repository_name: ${{ inputs.repository_name }}
          environment: ${{ inputs.us_environment_name }}
          docker_hub_user: ${{ secrets.docker_hub_user }}
          docker_hub_password: ${{ secrets.docker_hub_password }}
          current_tag: ${{ needs.params.outputs.short_sha }}
          should_tag_image: false
      - name: Assign variable
        id: secret
        run: echo '::set-output name=secret::${{ secrets.slack_production_webhook }}'
      - name: Notify Slack on deployment
        if:  steps.secret.outputs.secret
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: Production
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/67857107?s=40&v=4
          SLACK_MESSAGE: '${{ github.actor }} has deployed ${{ inputs.repository_name }} to ${{ inputs.us_environment_name }} :rocket:'
          SLACK_TITLE: ${{ inputs.repository_name }} to ${{ inputs.us_environment_name }}
          SLACK_USERNAME: ${{ github.actor }}
          SLACK_WEBHOOK: ${{ secrets.slack_production_webhook }}
          MSG_MINIMAL: Commit,actions url

  deploy-to-global:
    name: Deploy to All Global Environments
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.global_environment_name }}
    needs:
      - params
      - deploy-to-us
    steps:
      - name: Checkout ${{ inputs.repository_name }}
        uses: actions/checkout@v4
        with:
          path: code
          repository: frontegg/${{ inputs.repository_name }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.admin_github_token }}
      - name: Checkout workflows
        uses: actions/checkout@v4
        with:
          repository: frontegg/workflows
          path: workflows
          ref: ${{ inputs.workflows_version }}
      - name: 'Deploy to Production Global'
        uses: ./workflows/.github/shared-actions/tag-versions
        with:
          github_token: ${{ secrets.admin_github_token }}
          repository_name: ${{ inputs.repository_name }}
          environment: ${{ inputs.global_environment_name }}
          docker_hub_user: ${{ secrets.docker_hub_user }}
          docker_hub_password: ${{ secrets.docker_hub_password }}
          current_tag: ${{ needs.params.outputs.short_sha }}
          should_tag_image: false
      - name: Assign variable
        id: secret
        run: echo '::set-output name=secret::${{ secrets.slack_production_webhook }}'
      - name: Notify Slack on deployment
        if: steps.secret.outputs.secret
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: Production
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/67857107?s=40&v=4
          SLACK_MESSAGE: '${{ github.actor }} has deployed ${{ inputs.repository_name }} to ${{ inputs.global_environment_name }} :rocket:'
          SLACK_TITLE: ${{ inputs.repository_name }} to ${{ inputs.global_environment_name }}
          SLACK_USERNAME: ${{ github.actor }}
          SLACK_WEBHOOK: ${{ secrets.slack_production_webhook }}
          MSG_MINIMAL: Commit,actions url
