name: Main Service Deployment Workflow

on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
      repository_name:
        type: string
        required: true
      has_hybrid:
        required: false
        default: false
        type: boolean
      staging_environment_name:
        required: false
        default: staging
        type: string
      au_environment_name:
        required: false
        default: production-au
        type: string
      us_environment_name:
        required: false
        default: production-us
        type: string
      global_environment_name:
        required: false
        default: production-global
        type: string
      build_image_script:
        required: false
        default: ./ci/build-and-publish-image.sh
        type: string
      build_hybrid_image_script:
        required: false
        default: ./ci/build-and-publish-hybrid-image.sh
        type: string
      contains_code_changes:
        required: false
        default: true
        type: boolean
    secrets:
      npm_token:
        description: 'Npm Token'
        required: true
      docker_hub_password:
        description: 'Docker Hub Password'
        required: true
      docker_hub_user:
        description: 'Docker Hub User'
        required: true
      admin_github_token:
        description: 'Github repository admin token'
        required: true
      slack_production_webhook:
        description: 'Slack webhook token'
        required: false

jobs:
  main-with-image:
    name: Build Image and deploy
    if: ${{ github.event.inputs.contains_code_changes }}
    uses: frontegg/workflows/.github/workflows/main-with-image.yaml@master
    with:
      tag: ${{ github.event.inputs.tag }}
      repository_name: ${{ github.event.inputs.repository_name }}
      has_hybrid: ${{ github.event.inputs.has_hybrid }}
      staging_environment_name: ${{ github.event.inputs.staging_environment_name }}
      au_environment_name: ${{ github.event.inputs.au_environment_name }}
      us_environment_name: ${{ github.event.inputs.us_environment_name }}
      global_environment_name: ${{ github.event.inputs.global_environment_name }}
      build_image_script: ${{ github.event.inputs.build_image_script }}
      build_hybrid_image_script: ${{ github.event.inputs.build_hybrid_image_script }}
      should_tag_image: true
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
      docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
      admin_github_token: ${{ secrets.GH_REPOSITORY_ADMIN_TOKEN }}
      slack_production_webhook: ${{ secrets.SLACK_PRODUCTION_WEBHOOK }}

  main-without-image:
    name: Deploy
    if: ${{ !github.event.inputs.contains_code_changes }}
    uses: frontegg/workflows/.github/workflows/main-without-image.yaml@master
    with:
      tag: ${{ github.event.inputs.tag }}
      repository_name: ${{ github.event.inputs.repository_name }}
      has_hybrid: ${{ github.event.inputs.has_hybrid }}
      staging_environment_name: ${{ github.event.inputs.staging_environment_name }}
      au_environment_name: ${{ github.event.inputs.au_environment_name }}
      us_environment_name: ${{ github.event.inputs.us_environment_name }}
      global_environment_name: ${{ github.event.inputs.global_environment_name }}
      build_image_script: ${{ github.event.inputs.build_image_script }}
      build_hybrid_image_script: ${{ github.event.inputs.build_hybrid_image_script }}
      should_tag_image: false
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
      docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
      admin_github_token: ${{ secrets.GH_REPOSITORY_ADMIN_TOKEN }}
      slack_production_webhook: ${{ secrets.SLACK_PRODUCTION_WEBHOOK }}
