name: Remove a single venv

on:
  workflow_call:
    inputs:
      venvId:
        description: 'Set the venvId to remove'
        required: true
        type: string
      gracePeriodInMinutes:
        description: 'Set the grace period before removing venv, default is 0'
        required: false
        type: string
    secrets:
      admin_github_token:
        description: 'Github repository admin token'
        required: true

jobs:
  remove-venv:
    name: Remove Venv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          repository: frontegg/workflows
          ref: yarn37
          path: workflows
      - uses: ./workflows/.github/shared-actions/remove-single-venv
        name: Remove venv files
        id: venv-actions
        with:
          admin_github_token: ${{ secrets.admin_github_token }}
          venvRepoDirectory: ${{ github.workspace }}/venv/environments
          venvId: ${{ inputs.venvId }}
          gracePeriodInMinutes: ${{ inputs.gracePeriodInMinutes }}
