name: Remove a single venv

on:
  workflow_call:
    inputs:
      venvId:
        description: 'Set the venvId to remove'
        required: true
        type: string
    secrets:
      admin_github_token:
        description: 'Github repository admin token'
        required: true

jobs:
  remove-venv:
    name: Remove Venv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v3
        with:
          repository: frontegg/workflows
          path: workflows
      - uses: ./workflows/.github/shared-actions/remove-single-venv
        name: Remove venv files
        id: venv-actions
        with:
          admin_github_token: ${{ secrets.admin_github_token }}
          venvRepoDirectory: ${{ github.workspace }}/venv/environments
          venvId: ${{ inputs.venvId }}

  clean-namespace:
    name: Clean Namespace
    needs: [ remove-venv ]
    runs-on: [ self-hosted ]
    steps:
      - name: Install kubectl
        id: install
        uses: azure/setup-kubectl@v3
      - name: Get Token
        run: |
          echo "KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" >> $GITHUB_ENV
        shell: bash
      - name:
        run: |
          kubectl "--token=${{ env.KUBE_TOKEN }}" delete namespace ${{ inputs.venvId }}
        shell: bash
