name: Validate deployment
on:
  workflow_call:
    secrets:
      admin_github_token:
        description: 'The github token'
        required: true
      slack_production_webhook:
        description: 'Slack webhook token'
        required: true


jobs:
  validate_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: frontegg/deployment-validator
          token: ${{ secrets.admin_github_token }}
          ref: master
          path: ./deployment-validator
      - name: Verify version
        id: versions_verifier
        uses: ./deployment-validator
        env: 
          admin_github_token: ${{ secrets.admin_github_token }}
      - name: Notify Slack on deployment
        if: steps.versions_verifier.outputs.author
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: Production
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: https://avatars.githubusercontent.com/u/67857107?s=40&v=4
          SLACK_MESSAGE: 'Dear ${{ steps.versions_verifier.outputs.author }} please deploy ${{ github.repository }} to ${{ steps.versions_verifier.outputs.nonSyncedEnvs }}'
          SLACK_TITLE: Un-deployed commits detected on master
          SLACK_USERNAME: Github
          SLACK_WEBHOOK: ${{ secrets.slack_production_webhook }}